export const CHANGE_FIELD = 'CHANGE_FIELD';
export const CHANGE_PARTITION = 'CHANGE_PARTITION';
export const CREATE_PARTITION = 'CREATE_PARTITION';
export const CLEAR_PARTITION = 'CLEAR_PARTITION';
export const CLEAR_FIELD = 'CLEAR_FIELD';
export const DELETE_PARTS = 'DELETE_PARTS';
